--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "PJT"."BOARD" 
   (	"BNO" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"TRADE" NUMBER(1,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(500 BYTE), 
	"PRICE" NUMBER, 
	"PICK" CHAR(1 BYTE), 
	"STAG" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOARD_FILE_LIST
--------------------------------------------------------

  CREATE TABLE "PJT"."BOARD_FILE_LIST" 
   (	"FNO" NUMBER, 
	"BNO" NUMBER, 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"PATH" VARCHAR2(300 BYTE), 
	"ORIGINFILENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUY_LIST
--------------------------------------------------------

  CREATE TABLE "PJT"."BUY_LIST" 
   (	"ID" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"BUYNO" NUMBER, 
	"BNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PJT"."MEMBER" 
   (	"ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELL" VARCHAR2(12 BYTE), 
	"GRADE" NUMBER(2,0), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"POINT" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "PJT"."REVIEW" 
   (	"RNO" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"REVIEW_CONTENT" VARCHAR2(100 BYTE), 
	"REVIEW_POINT" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SELL_LIST
--------------------------------------------------------

  CREATE TABLE "PJT"."SELL_LIST" 
   (	"ID" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"SELLNO" NUMBER, 
	"BNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "PJT"."TAG" 
   (	"TAGID" VARCHAR2(50 BYTE), 
	"STAG" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PJT.BOARD
SET DEFINE OFF;
REM INSERTING into PJT.BOARD_FILE_LIST
SET DEFINE OFF;
REM INSERTING into PJT.BUY_LIST
SET DEFINE OFF;
REM INSERTING into PJT.MEMBER
SET DEFINE OFF;
REM INSERTING into PJT.REVIEW
SET DEFINE OFF;
REM INSERTING into PJT.SELL_LIST
SET DEFINE OFF;
REM INSERTING into PJT.TAG
SET DEFINE OFF;
Insert into PJT.TAG (TAGID,STAG) values ('samsung',0);
Insert into PJT.TAG (TAGID,STAG) values ('apple',1);
Insert into PJT.TAG (TAGID,STAG) values ('lg',2);
Insert into PJT.TAG (TAGID,STAG) values ('etc',3);
Insert into PJT.TAG (TAGID,STAG) values ('skt',4);
Insert into PJT.TAG (TAGID,STAG) values ('kt',5);
Insert into PJT.TAG (TAGID,STAG) values ('lgu+',6);
Insert into PJT.TAG (TAGID,STAG) values ('self',7);
Insert into PJT.TAG (TAGID,STAG) values ('wifi',8);
Insert into PJT.TAG (TAGID,STAG) values ('5g',9);
Insert into PJT.TAG (TAGID,STAG) values ('4g',10);
Insert into PJT.TAG (TAGID,STAG) values ('3g',11);
Insert into PJT.TAG (TAGID,STAG) values ('2g',12);
Insert into PJT.TAG (TAGID,STAG) values ('appleos',13);
Insert into PJT.TAG (TAGID,STAG) values ('android',14);
Insert into PJT.TAG (TAGID,STAG) values ('new',15);
Insert into PJT.TAG (TAGID,STAG) values ('good',16);
Insert into PJT.TAG (TAGID,STAG) values ('soso',17);
Insert into PJT.TAG (TAGID,STAG) values ('bad',18);
Insert into PJT.TAG (TAGID,STAG) values ('definite_change',19);
Insert into PJT.TAG (TAGID,STAG) values ('usim',20);
Insert into PJT.TAG (TAGID,STAG) values ('discount',21);
Insert into PJT.TAG (TAGID,STAG) values ('guarantee',22);
Insert into PJT.TAG (TAGID,STAG) values ('full',23);
Insert into PJT.TAG (TAGID,STAG) values ('omission',24);
Insert into PJT.TAG (TAGID,STAG) values ('only',25);
Insert into PJT.TAG (TAGID,STAG) values ('p1',26);
Insert into PJT.TAG (TAGID,STAG) values ('p2',27);
Insert into PJT.TAG (TAGID,STAG) values ('p3',28);
Insert into PJT.TAG (TAGID,STAG) values ('p4',29);
Insert into PJT.TAG (TAGID,STAG) values ('p5',30);
Insert into PJT.TAG (TAGID,STAG) values ('p6',31);
--------------------------------------------------------
--  DDL for Index BOARD_FILE_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BOARD_FILE_LIST_PK" ON "PJT"."BOARD_FILE_LIST" ("FNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BOARD_PK" ON "PJT"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUY_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BUY_LIST_PK" ON "PJT"."BUY_LIST" ("BUYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."MEMBER_PK" ON "PJT"."MEMBER" ("ID", "NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELL_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."SELL_LIST_PK" ON "PJT"."SELL_LIST" ("SELLNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."STAG_PK" ON "PJT"."TAG" ("STAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BOARD_PK" ON "PJT"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_FILE_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BOARD_FILE_LIST_PK" ON "PJT"."BOARD_FILE_LIST" ("FNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BUY_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."BUY_LIST_PK" ON "PJT"."BUY_LIST" ("BUYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."MEMBER_PK" ON "PJT"."MEMBER" ("ID", "NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SELL_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."SELL_LIST_PK" ON "PJT"."SELL_LIST" ("SELLNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PJT"."STAG_PK" ON "PJT"."TAG" ("STAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "PJT"."BOARD" MODIFY ("STAG" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PJT"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" MODIFY ("TRADE" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_FILE_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."BOARD_FILE_LIST" ADD CONSTRAINT "BOARD_FILE_LIST_PK" PRIMARY KEY ("FNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PJT"."BOARD_FILE_LIST" MODIFY ("BNO" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BOARD_FILE_LIST" MODIFY ("FNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUY_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."BUY_LIST" ADD CONSTRAINT "BUY_LIST_PK" PRIMARY KEY ("BUYNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PJT"."BUY_LIST" MODIFY ("BNO" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BUY_LIST" MODIFY ("BUYNO" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BUY_LIST" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "PJT"."BUY_LIST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PJT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID", "NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PJT"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "PJT"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "PJT"."REVIEW" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "PJT"."REVIEW" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SELL_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."SELL_LIST" ADD CONSTRAINT "SELL_LIST_PK" PRIMARY KEY ("SELLNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PJT"."SELL_LIST" MODIFY ("BNO" NOT NULL ENABLE);
  ALTER TABLE "PJT"."SELL_LIST" MODIFY ("SELLNO" NOT NULL ENABLE);
  ALTER TABLE "PJT"."SELL_LIST" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "PJT"."SELL_LIST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "PJT"."TAG" MODIFY ("STAG" NOT NULL ENABLE);
  ALTER TABLE "PJT"."TAG" MODIFY ("TAGID" NOT NULL ENABLE);
  ALTER TABLE "PJT"."TAG" ADD CONSTRAINT "STAG_PK" PRIMARY KEY ("STAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "PJT"."BOARD" ADD CONSTRAINT "BOARD_MEMBER_FK" FOREIGN KEY ("ID", "NICKNAME")
	  REFERENCES "PJT"."MEMBER" ("ID", "NICKNAME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PJT"."BOARD" ADD CONSTRAINT "STAG_FK" FOREIGN KEY ("STAG")
	  REFERENCES "PJT"."TAG" ("STAG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_FILE_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."BOARD_FILE_LIST" ADD CONSTRAINT "BOARD_FILE_LIST_BOARD_FK" FOREIGN KEY ("BNO")
	  REFERENCES "PJT"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUY_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."BUY_LIST" ADD CONSTRAINT "BUY_LIST_BOARD_FK" FOREIGN KEY ("BNO")
	  REFERENCES "PJT"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PJT"."BUY_LIST" ADD CONSTRAINT "BUY_LIST_MEMBER_FK" FOREIGN KEY ("ID", "NICKNAME")
	  REFERENCES "PJT"."MEMBER" ("ID", "NICKNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "PJT"."REVIEW" ADD CONSTRAINT "REVIEW_MEMBER_FK" FOREIGN KEY ("ID", "NICKNAME")
	  REFERENCES "PJT"."MEMBER" ("ID", "NICKNAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SELL_LIST
--------------------------------------------------------

  ALTER TABLE "PJT"."SELL_LIST" ADD CONSTRAINT "SELL_LIST_BOARD_FK" FOREIGN KEY ("BNO")
	  REFERENCES "PJT"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PJT"."SELL_LIST" ADD CONSTRAINT "SELL_LIST_MEMBER_FK" FOREIGN KEY ("ID", "NICKNAME")
	  REFERENCES "PJT"."MEMBER" ("ID", "NICKNAME") ON DELETE CASCADE ENABLE;
